image: Visual Studio 2017

before_build:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\msbuild" /t:restore Library.UTest\Library.UTest.csproj'

build_script:
  - '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\bin\msbuild" /t:build Library.UTest\Library.UTest.csproj'

test_script:
  - C:\Tools\NUnit3\nunit3-console Library.UTest\bin\Debug\netcoreapp1.0\Library.UTest.dll
