before_build:
  - dotnet restore Library.UTest\Library.UTest.csproj

build_script:
  - dotnet build Library.UTest\Library.UTest.csproj

test_script:
  - dotnet test Library.UTest\Library.UTest.csproj
